Engine:
  WithHostPorts: 0.0.0.0:8000
  WithStreamBody: true
  registry:
    serviceName: gateway
    addr: "127.0.0.1:8000"
    weight: 10
    tags: []
Minio:
  Endpoint: 127.0.0.1:9000
  AccessKeyID: minioadmin
  SecretAccessKey: minioadmin
  UseSSL: false