// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	comment "gateway/biz/router/comment"
	favorite "gateway/biz/router/favorite"
	feed "gateway/biz/router/feed"
	message "gateway/biz/router/message"
	publish "gateway/biz/router/publish"
	relation "gateway/biz/router/relation"
	user "gateway/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	message.Register(r)

	relation.Register(r)

	favorite.Register(r)

	feed.Register(r)

	comment.Register(r)

	publish.Register(r)

	user.Register(r)

}
